blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from . import views
from .views import user_logout, Home, Detaisl_View, EditPostView, DeletePostView, LikeView, AddCommentpage

app_name = 'blog'

urlpatterns = [
    # path('', views.post, name='post'),
    # path('create/', views.create_post, name='create_pots'),
    # path('<int:primary_key>/edit/', views.post_edit, name='post_edit'),
    # path('<int:primary_key>/delete/', views.post_delete, name='post_delete'),
    path('', views.home, name='home'),
    path('art/<int:title_id>', views.detail, name='detail'),  # add pots
    path('add_fields/', views.fill_in_form, name='add_fields'),  # add pots
    # path('add_fields/', AddPost.as_view(), name='add_fields'), # add pots

    path('<int:title_id>/<str:author_name>/', views.user_blog, name='user_blog'),
    path('signup/', views.signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),  # This included log in and log out views by default
    # path('logout/', views.user_logout, name='logout')
    path('logout/', LogoutView.as_view(), name='logout'),
    path('post/', Home.as_view(), name='home_class'),  # Test Delete later
    path('article/<int:pk>', Detaisl_View.as_view(), name='article'),  # Test Delete later
    path('<int:pk>/edit', EditPostView.as_view(), name='edit_post'),  # Edit
    path('delete/<int:pk>', DeletePostView.as_view(), name='delete_blog'),
    path('like/<int:pk>', LikeView, name='like_post'),
    # path('article/<int:pk>/comment/', AddCommentpage.as_view(), name='post_comment'),
    path('article/<int:pk>/comment/', AddCommentpage.as_view(), name='post_comment'),

    # movie/1
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_and_vlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# from ..api.models import BlogResource

# from DjangoBlogProject.blog_and_vlog.blog_and_vlog.settings import MEDIA_URL
# blog_resource = BlogResource

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('django.contrib.auth.urls')), # This will take care of all url Login Logout
    path('', include('users.urls')),

    # path('add_fields/', views.fill_in_form, name='add_fields'),

    # path('api/', include(blog_resource.urls)),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.timezone import make_aware
from django.utils import timezone
from datetime import datetime
# from django.contrib.auth.models import User
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
from django.db import models
from django.utils import timezone

# Add a Rich text editor to a Django blog
# from ckeditor.fields import RichTextField




class Fields(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    authorHidden = models.CharField(max_length=255, null=True)
    updated_on = models.DateTimeField(default=timezone.now)
    # content = RichTextField(blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    # content = models.TextField()
    created_on = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to='images_uploaded', null=True)
    video = models.FileField(upload_to='videos_uploaded', null=True)
    like = models.ManyToManyField(User, related_name='blog_like') # assiciate many together

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    category_blog = models.CharField(max_length=255, default='coding')

    def __str__(self):
        return self.title + ' | ' + str(self.user)  # an objects turn in to string

    def total_likes(self):
        return self.like.count()

class Category_blog(models.Model):
    name = models.CharField(max_length=255)

# associate with user app with this
class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE) #when we delete user automatically delete
    bio = models.TextField()
    picture_profile =models.ImageField(null=True, blank=True, upload_to='images/profile/')

    facebook_url = models.CharField(max_length=255, null=True, blank=True,)
    twitter_url = models.CharField(max_length=255, null=True, blank=True, )
    instagram_url = models.CharField(max_length=255, null=True, blank=True, )


    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('blog:home')

class Add_comment(models.Model):
    # we call comment then grab all the comment
    post_title = models.ForeignKey(Fields, related_name="comments", on_delete=models.CASCADE) #automatically delete blog post that
    body = models.TextField()
    added_date = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=255)

    def __str__(self):
        return '%s - %s' % (self.post_title.title, self.name)
#     will show post title that we are comment on


# a. title (character field)
# b. author (character field)
# c. updated_on (date/time field)
# d. content (text field)
# e. created_on (date/time field)
# f. image (img field)
# g. video (video field)


blog/forms.py
# import form
# forms.py
from django import forms
from django.shortcuts import get_object_or_404

from .models import Fields
from django import forms
from django.contrib.auth.forms import UserCreationForm  # built in forms for user creation
from .models import Add_comment


class FillInForms(forms.ModelForm):
    class Meta:
        model = Fields
        fields = ('title', 'author','authorHidden', 'updated_on', 'content', 'created_on', 'image', 'video')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            # JS will automalically looks for value id
            'author': forms.TextInput(attrs={'class': 'form-control'}),
            'authorHidden': forms.TextInput(attrs={'class': 'form-control', 'value': '', 'id': 'name', 'type':'hidden'}),
            'updated_on': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'created_on': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'user': forms.Select(attrs={'class': 'form-control'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'video': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

        def get_object(self, queryset=None):
            title_id = self.kwargs.get('title_id')
            return get_object_or_404(Fields, pk=title_id)


# for edit in view
class EditForms(forms.ModelForm):
    class Meta:
        model = Fields
        fields = ('title', 'updated_on', 'content', 'image', 'video')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'This is Title place holder.'}),
            'updated_on': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'video': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Add_comment
        fields = ('name','body')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),

        }

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
# get an object if it does not exits return 404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse

# Create View
# from .forms import PostStructure
from .models import Fields, Add_comment
from .forms import FillInForms, EditForms, AddCommentForm

# Sign up view
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
# CreateView # bring it back the way it set to datatbase.
from django.urls import reverse_lazy


def home(request):
    field = Fields.objects.all().order_by('-updated_on')
    return render(request, 'index.html', {'field': field})


# ordering by id


# Id part for next page
def detail(request, title_id):
    # look up the code
    # Grabe th id from Fields look up the id of that blog
    # assign to stuffs that take total like and get calculate it
    # thing = get_object_or_404(Fields, pk=title_id)
    title = get_object_or_404(Fields, pk=title_id)
    total_like = title.total_likes()  # from model

    # request user id and pass unlike variable in context
    unlike = False
    if title.like.filter(id=request.user.id).exists():
        unlike = True
    context = {
        'title': title,
        'total_like': total_like,
        'unlike': unlike,

    }
    return render(request, 'detail.html', context)


# to make sure only logged-in can add a blog
@login_required
def fill_in_form(request):
    if request.method == "POST":
        form = FillInForms(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('blog:user_blog', title_id=post.pk,
                            author_name=post.user.username)  # redirect to a success page or the list of fields
    else:
        form = FillInForms()
    return render(request, 'form.html', {'form': form})


from django.contrib.auth.decorators import login_required


# To redirect to that specific page belong to that user with id/author name urls
@login_required
def user_blog(request, title_id, author_name):
    title = get_object_or_404(Fields,
                              pk=title_id)  # View logic: checking th author name from the urls mach the username of the associated user this will ensure only the rig user can access
    if title.user.username != author_name or title.user != request.user:  # with this changes, The URL for user blog will included both the 'title_id' and 'author_name'
        raise Http404("You don't have permission to view this post.")
    return render(request, 'user_blog.html', {'title': title})


# Signup View
def signup(request):
    if request.method == 'POST':
        form_signup = UserCreationForm(request.POST)
        if form_signup.is_valid():
            form_signup.save()
            return redirect('login')  # redirect to login after sign up
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form_signup': form_signup})


def user_logout(request):
    return LogoutView.as_view(next_page='blog:home')(request)


# Test Delete later
class Home(ListView):
    model = Fields
    template_name = 'post.html'


# Test Delete later
class Detaisl_View(DetailView):
    model = Fields
    template_name = 'post_create.html'


# class AddPost(CreateView):
#     model = Fields
#     template_name = 'form.html'
#     fields = '__all__'

# Build in class edit post
class EditPostView(UpdateView):
    model = Fields
    form_class = EditForms
    template_name = 'update_blog.html'

    # If you're using 'pk' or 'slug' in your URL patterns, you do not need to override get_object.
    # However, if you have a custom URL pattern, you would override it like so:
    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')  # This should match the keyword used in your URL pattern
        return get_object_or_404(Fields, pk=pk)

    # Define this method if you want to customize the success URL.
    def get_success_url(self):
        # Make sure the keyword argument matches what's expected in your URL pattern
        return reverse('blog:detail', kwargs={'title_id': self.object.pk})

    #     # Assuming self.object is the post object and has an 'id' attribute


class DeletePostView(DeleteView):
    model = Fields
    # success_url = reverse_lazy('blog:home')
    template_name = 'delete_blog.html'

    def get_success_url(self):
        # You can include any logic you want here to determine the correct success URL.
        return reverse('blog:home')  #


def LikeView(request, pk):
    title = get_object_or_404(Fields, id=request.POST.get('title_id'))
    #     Whta ever title id is that looks up in that post and assign to post variable and save to the table
    #     We savinh a like from the user to see who like thi spost

    # pass in the request and request contain user id for login. If we login look up whether like has been like by user 1
    #     If clicked and if it except then we want to unlike the post and remove by user
    if title.like.filter(id=request.user.id).exists():
        title.like.remove(request.user)
    else:
        title.like.add(request.user)
    # if it doesn' alreay exit then we just add the like an dchenge like to True and add like as Fale
    # After unlike like will be false . after like it like will be true

    # title.like.add(request.user)
    # redirect to the same page, instaed of returning render request or return lazy. first import Http
    return HttpResponseRedirect(reverse('blog:detail', args=[str(pk)]))

# Add comment
class AddCommentpage(CreateView):
    model = Add_comment
    form_class = AddCommentForm
    template_name = 'post_comment.html'
    # fields = '__all__'

    def form_valid(self, form):
        form.instance.post_title_id = self.kwargs['pk']

        return super().form_valid(form)
    success_url = reverse_lazy('blog:home')
# In your AddCommentpage class view, you are setting form.instance.id = self.kwargs['pk'], but you should be setting the post_title_id since id would refer to the primary key of the Add_comment instance (which is auto-generated).

blog/templates/delete_blog.html
{% extends 'base.html' %}
{% block title %}Delete Blog ...{% endblock %}
{% block content %}


    {#        <p>Are you sure do you want to delete {{ object }}?</p>#}

    {#    <h3>Delete: {{ post.title }}</h3>#}
    {#    current user:  {{ user.id }}#}
    {#    blog author: {{ user.id }}#}
    <div class="card">
        <div class="card-header bg-dark text-white">
            <h4>Delete blog..</h4>
        </div>
        <div class="card-body">
            <h5 class="card-title">Confirm Deletion</h5>
            <p class="card-text">Are you sure do you want to delete {{ object }}?</p>
            {% if user.is_authenticated %}
                {#        {% if user.id == title.user.id %}#}
{#                <br>#}
                <div class="form-group">
                    <form method="POST" class="d-inline">
                        {% csrf_token %}
                        {#                        <input type="submit" value="Confirm">#}
                        <button type="submit" class="btn btn-danger">Confrim Delete</button>
                    </form>

                    <a class="btn btn-secondary" href="{% url 'blog:home' %}">Cancel</a>
                </div>
                {#        {% endif %}#}
            {% else %}
                <p class="alert alert-danger">You are not allows here.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

blog/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ title.title }} {% endblock %}

{% block content %}
    {#    current user:  {{ user.id }}#}
    {#    blog author: {{ title.user.id }}#}
    {#    <p>user page {{ page_user }}</p>#}



    <div class="container mt-4">
        <div class="mb-3">

            <h2 class="display-7">{{ title.title }}</h2>


            {#    if somebody alredy like it we will unlike, else they havnt like then we shows like button#}
            <form action="{% url 'blog:like_post' title.pk %}" method="POST">{% csrf_token %}
                {% if user.is_authenticated %}
                    {% if unlike %}
                        <button type="submit" , name="title_id" , value="{{ title.id }}" ,
                                class="btn btn-danger btn-sm me-2">
                            <i class="bi bi-heart-fill"></i>
                            UnLike
                        </button>
                    {% else %}
                        <button type="submit" , name="title_id" , value="{{ title.id }}" ,
                                class="btn btn-primary btn-sm me-2">
                            <i class="bi bi-heart"></i>
                            Like
                        </button>

                    {% endif %}
                    <span class="badge bg-secondary">{{ total_like }} Likes</span>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login To like</a>
                    </li>
                {% endif %}
            </form>

            {#    this title.id will pas 15 into the backend#}
            <hr>
            <small>
                <p class="text-muted">By: {{ title.author }} -
                    {{ title.created_on }}

                    {% if user.is_authenticated %}
                        {% if user.id == title.user.id %}
                            <a class="badge badge-primary text-wrap text-decoration-none" style="width: 3rem;"
                               href="{% url 'blog:edit_post' title.id %}"> Edit</a>

                            <a class="badge badge-primary text-wrap text-decoration-none btn btn-danger"
                               style="width: 3rem;"
                               href="{% url 'blog:delete_blog' title.pk %}">Delete</a>
                            </p>
                            </small>
                        {% endif %}
                    {% endif %}


            <br>
            {{ title.content|safe }}
            <br>
        </div>

        <div class=" row row-cols-1 row-cols-md-2 g-4">
            <div class="container mt-4 centered-content">
                {#                    <div class="p-3 border bg-light">#}
                {% if title.video %}
                    {#                        <video class="img-fluid p-3 bg-light border rounded" controls>#}
                    <video class="img-fluid" controls>
                        <source src="{{ title.video.url }}" type="video/mp4">
                        Your Browser does not support the video tags
                    </video>
                {% else %}
                    <h1>No video Display</h1>
                {% endif %}
            </div>

            {#            <div class="col-md-6 mb-3">#}
            {#                    <div class="p3 bg-light border rounded">#}
            {#                        <div class="img-fluid p-3 bg-light border rounded" control>#}
            {#                {% if title.image %}#}
            {#                    <img class="img-fluid rounded" style=" object-fit: cover;"#}
            {#                         src="{{ title.image.url }}"#}
            {#                         alt="{{ title.title }}" controls>#}
            {#                {% else %}#}
            {#                    <h1>No data display</h1>#}
            {#                {% endif %}#}
            {#                        </div>#}
            {#                    </div>#}
            {#            </div>#}

            {#            <div class="col-md-6 mb-3">#}
            {#                    <div class="p3 bg-light border rounded">#}
            {#                        <div class="img-fluid p-3 bg-light border rounded" control>#}
            {#                {% if title.image %}#}
            {#                    <img class="img-fluid rounded" style=" object-fit: cover;"#}
            {#                         src="{{ title.image.url }}"#}
            {#                         alt="{{ title.title }}" controls>#}
            {#                {% else %}#}
            {#                    <h1>No data display</h1>#}
            {#                {% endif %}#}
            {#                        </div>#}
            {#                    </div>#}
            {#            </div>#}
        </div>


        {#    Profile#}
        {#    <img src="{{ title.user.profile.picture_profile.url }}" alt="photo" width=100 height="100" class="rounded-pill">#}

        <div class="card mb-3 mt-3">
            <div class="card-header">
                {{ title.author }}
            </div>
            <div class=" header row g-0">
                <div class="col-md-2">

                    {% if title.user.profile.picture_profile %}

                        <img src="{{ title.user.profile.picture_profile.url }}" class="img-fluid rounded-start mt-2"
                             alt="Profile Picture">
                    {% else %}
                        <img src="{% static 'blog/images/img_1.png' %}" alt="card-img" width="100" height="100">
                    {% endif %}
                </div>
                <div class="col-md-10">
                    <div class="card-body">
                        {#                        <h5 class="card-title">{{ title.author }}</h5>#}
                        <p class="small text-muted">

                            {% if title.user.profile %}
                                <a href="{% url 'profile_page' title.user.id %}" class="text-muted me-2">Profile
                                    Page</a>
                            {% endif %}


                            {% if title.user.profile.facebook_url %}
                                <a href="{{ title.user.profile.facebook_url }}"
                                   class="text-muted me-2 ">Facbook </a>
                            {% endif %}
                            {% if title.user.profile.twitter_url %}
                                <a href="{{ title.user.profile.twitter_url }}" class="text-muted me-2">Twitter </a>
                            {% endif %}
                            {% if title.user.profile.instagram_url %}
                                <a href="{{ title.user.profile.instagram_url }} "
                                   class="text-muted me-2">Instagram</a>
                            {% endif %}
                        </p>

                        <p class="card-text">{{ title.user.profile.bio }}</p>
                        <p class="card-text"><small class="text-body-secondary text-muted">Last updated 3 mins
                            ago</small></p>
                    </div>
                </div>
            </div>
        </div>

{#        br#}
        <hr>
        <div class="container mt-4">
            <h2 class="mb-3">Comments..</h2>
            {#    {{ title.comments.all }}#}
            {#our model is singular comment in model we set related name to comments and it will get thing out from comments#}
            <h6 class="text-muted">{{ title.comments.all.count }} Comment(s)</h6>
            {% if not title.comments.all %}
                <div class="alert alert-info" role="alert">
                    No comment Yet...<a href="{% url 'blog:post_comment' title.id %}">  Add comment</a>
                </div>
            {% else %}

                <br>
                {#        #}
                {% for comment in title.comments.all %}
                    {#        call from model#}
                    <div class="card mt-3">
                        <div class="card-body">
                            <h5 class="card-title">{{ comment.name }} </h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ comment.added_date }}</h6>
                            <p> {{ comment.body }}</p>
                        </div>
                    </div>
                {% endfor %}
                <br>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <a class="btn btn-primary" href="{% url 'blog:post_comment' title.id %} ">Add
                        comment</a>

                </div>
            {% endif %}
        </div>


        <br><br>
        {#    {{ title.content|safe }}#}
        <a href="{% url 'blog:home' %}">
            <button type="button" class="btn btn-secondary">Back</button>
        </a>
    </div>

    <br>
{% endblock %}

blog/templates/form.html
{#form.html#}

{% extends 'base.html' %}
{% block title %}Create a new blog post {% endblock %}



{% block content %}
    <div class="container">
        {#    <small>#}
        {#        By: {{ title.user }}#}
        {#    </small>#}
        {#    <hr>#}
        <div class="row">
            <div class="col-md-10 offset-md-1">
                <div class=" border-left-info shadow py-2">
                    <div class="card-header text-white text-center">
                        <h2 class="text-info-emphasis list-group-item list-group-item-dark p-3">Create New Blog ..</h2>
                    </div>
                    {% if user.is_authenticated %}
                        <div class="card m-3">
                        <div class="card-body p-3">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.media }}
                                {{ form.as_p }}
                                <div class="text-center">
                                    <button type="submit" class="btn btn-secondary text-center">Submit</button>
                                </div>
                            </form>

                        </div>
                        {#Just check value id of that persopn who is login#}
                        <script>
                            var name = "{{ user.id }}";
                            document.getElementById("name").value = name;
                        </script>
                    {% else %}
                        <div>
                            <p class="alert alert-warning" role="alert">You are not allows here.</p>1
                        </div>
                    {% endif %}
                    </div>
                </div>

            </div>

            {#        <h3 class="mb-4 text-info-emphasis"> Create New Blog ..</h3>#}
        </div>
    </div>

{% endblock %}

{#vThe enctype="multipart/form-data" attribute is necessary because the form includes file fields (ImageField and FileField).#}
{#form.as_p renders the form as a series of paragraphs, with each form field wrapped in a <p> tag. You can use form.as_table or form.as_ul for different renderings.#}

blog/templates/index.html
{% extends 'base.html' %}
{% block title %} Blog and Vlog Application{% endblock %}


{% block content %}
    <div class="card bg-dark text-white">
        <img class="img-fluid thumb-post"
             style="width: 100%; height: 250px">
        <div class="card-img-overlay">
            <br>
            <h1 class="card-title">Create your own post..</h1>
            <p class="card-text">Hey there! Got something cool or quirky to share? This blog's just the spot for you to
                drop your ideas and stories. Tell us, what's buzzing in your head? Let's hear what you've got!</p>
            <small><p class="card-text">Last updated 3 mins ago</p></small>
        </div>
    </div>



    <div class="container mt-3">
        <div class="row">

            <hr>
            {#            <br>#}
            {#        display current user and blog author #}
            {#            <div class="col-12">#}
            {#                <div class="mb-3">#}
            {#                    Current user:{{ user.id }} <br>#}
            {#                    Blog author: {{ title.user.id }}#}
            {#                </div>#}
            {#            </div>#}

            {#        Grid #}
            {% for m in field %}
                <div class="col-md-3 mb-4"> {# change this line to use col-md-3 for 4 columns            #}
                    <div class="card h-100">
                        {#                    Image#}
                        {% if m.image %}
                            <a href="{% url 'blog:detail' m.id %}" class="text-dark text-decoration-none"><img
                                    src="{{ m.image.url }}" class="card-img-top" tabindex="0" data-bs-toggle="tooltip"
                                    title="{{ m.title }}" alt="{{ m.title }}" style="height: 200px; object-fit: cover"></a>
                            {#                            <img src="{{ m.image.url }}" class="card-img-top" alt="{{ m.title }}" style="height: 200px; object-fit: cover;">#}
                        {% endif %}

                        <div class="card-body">
                            <h6 class="card-title text-center blockquote font-weight-bolder" tabindex="0"
                                data-bs-toggle="tooltip" title="{{ m.title }}">
                                <a href="{% url 'blog:detail' m.id %}"
                                   class="text-dark text-decoration-none">{{ m.title }}</a>
                            </h6>
                            <br>
                            {#                            <p>{{ m.user }}</p>#}
                            <p class="blockquote-footer text-center"><strong>Author:</strong> {{ m.author }}</p>

                            {#                            <p class="card-text">{{ m.content|safe }}</p>#}
                        </div>
                        <div class="card-footer text-center">
                            <small class="text-muted"> {{ m.created_on|date:"d M Y" }}</small>
                            {% if user.is_authenticated and user.id == m.user.id %}
                                <a class="badge badge-primary text-wrap text-decoration-none" style="width: 3rem;"
                                   href="{% url 'blog:edit_post' m.id %}">Edit</a> |
                                <a class="badge badge-primary text-wrap text-decoration-none" style="width: 3.5rem;"
                                   href="{% url 'blog:delete_blog' m.pk %}">Delete</a>

                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock %}

blog/templates/post.html
{#{% extends 'base.html' %}#}

<h1>Post</h1>
{% for post in object_list %}
{#    <li><a href="{% url 'blog:article' post.pk %}">{{ post.title }}</a></li>#}
    <a href="{% url 'blog:article' post.pk %}">{{ post.title }}</a>

    {{ post.author}}
    {{ post.user}}
{#    {{ post.user.lastname_name }}#}

{% endfor %}