blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from . import views
from .views import user_logout, Home, Detaisl_View, EditPostView, DeletePostView, LikeView, AddCommentpage

app_name = 'blog'

urlpatterns = [
    # path('', views.post, name='post'),
    # path('create/', views.create_post, name='create_pots'),
    # path('<int:primary_key>/edit/', views.post_edit, name='post_edit'),
    # path('<int:primary_key>/delete/', views.post_delete, name='post_delete'),
    path('', views.home, name='home'),
    path('art/<int:title_id>', views.detail, name='detail'),  # add pots
    path('add_fields/', views.fill_in_form, name='add_fields'),  # add pots
    # path('add_fields/', AddPost.as_view(), name='add_fields'), # add pots

    path('<int:title_id>/<str:author_name>/', views.user_blog, name='user_blog'),
    path('signup/', views.signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),  # This included log in and log out views by default
    # path('logout/', views.user_logout, name='logout')
    path('logout/', LogoutView.as_view(), name='logout'),
    path('post/', Home.as_view(), name='home_class'),  # Test Delete later
    path('article/<int:pk>', Detaisl_View.as_view(), name='article'),  # Test Delete later
    path('<int:pk>/edit', EditPostView.as_view(), name='edit_post'),  # Edit
    path('delete/<int:pk>', DeletePostView.as_view(), name='delete_blog'),
    path('like/<int:pk>', LikeView, name='like_post'),
    # path('article/<int:pk>/comment/', AddCommentpage.as_view(), name='post_comment'),
    path('article/<int:pk>/comment/', AddCommentpage.as_view(), name='post_comment'),

    # movie/1
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_and_vlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# from ..api.models import BlogResource

# from DjangoBlogProject.blog_and_vlog.blog_and_vlog.settings import MEDIA_URL
# blog_resource = BlogResource

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('django.contrib.auth.urls')), # This will take care of all url Login Logout
    path('', include('users.urls')),

    # path('add_fields/', views.fill_in_form, name='add_fields'),

    # path('api/', include(blog_resource.urls)),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}This is a block post about.. {% endblock %}</title>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <style>
        .custom-hover, .nav_link {
            transition: background-color 0.3s ease; /* Smooth transition for the background */
            margin-bottom: 5px;
        {#padding-right: 20px/* Adjust this value as needed for your bottom margin */#}
        }

        .custom-hover:hover {
        {#text-decoration: underline;#} background-color: rgba(192, 192, 192);
            color: white; /* Light white blur */
        }
    </style>

</head>
<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary" style="margin-right: 20px;">
    <div class="container-fluid">
        <a class="navbar-brand" href="">

            {#      <img src="https://images.pexels.com/photos/982300/pexels-photo-982300.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="" width="30" height="30" class="d-inline-block align-text-top ms-3">#}
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto ">
                <li class="nav-item ms-auto">
                    <a class="nav-link custom-hover " aria-current="page" href="{% url 'blog:home' %}">Home</a>
                </li>

                {#                # Deal with user login and logout#}
                {% if user.is_authenticated %}
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link custom-hover" href="{% url 'blog:add_fields' %}">Create Blogs</a>
                        </li>


                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href=""
                               role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                <img
                                        src="{{ user.profile.picture_profile.url }}"

                                        class="rounded-circle"
                                        height="25"
                                        alt="Profile"
                                        loading="lazy"
                                />
                            </a>


                            <ul class="dropdown-menu dropdown-menu-end">

                                {% if user.profile.id %}
                                    <li>
                                        <a class="dropdown-item"
                                           href="{% url 'edit_profile_page' user.profile.id %}">Edit
                                            Profile Page </a>
                                    </li>

                                    <li>
                                        <a class="dropdown-item" href="{% url 'profile_page' user.profile.id %}">Show
                                            profile
                                            Page </a>
                                    </li>
                                {% else %}
                                    <li>
                                        <a class="dropdown-item" href="{% url 'create_profile_page' %}">Create
                                            Profile Page </a>
                                    </li>
                                {% endif %}
                                <li>
                                    <a class="dropdown-item" href="{% url 'edit_profile' %}">Setting </a>
                                </li>


                                <li>
                                    <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                                </li>
                            </ul>
                        </li>
                    </ul>


                {% else %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    </ul>
                {% endif %}

            </ul>

        </div>
    </div>
</nav>

<main class="container">
    {% block content %}

    {% endblock %}

</main>

<!-- Adding a footer -->
<footer>
    <div class="text-center mt-4  p-2 bg-light">
        <p class="m-0 text-secondary text-muted">&copy; 2023 Blog and Vlog Application. All Rights Reserved.</p>
    </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>


</body>
</html>